/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        "surface-canvas": "#0F172A",
        "surface-panel": "#1E293B",
        "surface-recessed": "#0A0F1E",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "border-subtle": "#334155",
        "text-primary": "#E2E8F0",
        "text-dim": "#94A3B8",
        primary: "#4cd7f6",
        "primary-container": "#06b6d4",
        secondary: "#adc6ff",
        "secondary-container": "#0566d9",
        info: "#3B82F6",
        "status-safe": "#22C55E",
        "status-warn": "#F59E0B",
        "status-elevated": "#F97316",
        "status-danger": "#EF4444",
        "status-info": "#3B82F6",
      },
      spacing: {
        "space-2": "2px",
        "space-4": "4px",
        "space-6": "6px",
        "space-8": "8px",
        "space-10": "10px",
        "space-12": "12px",
        "space-16": "16px",
        "space-24": "24px",
        "nav-height": "56px",
        "banner-height": "44px",
        "footer-height": "28px",
        "dock-left-width": "200px",
        "dock-right-width": "240px",
        "decision-bar-height": "52px",
      },
      fontSize: {
        "headline-lg": ["20px", { lineHeight: "28px" }],
        "headline-md": ["16px", { lineHeight: "24px" }],
        "headline-sm": ["14px", { lineHeight: "20px" }],
        "body-lg": ["14px", { lineHeight: "20px" }],
        "body-md": ["13px", { lineHeight: "18px" }],
        "body-sm": ["12px", { lineHeight: "16px" }],
        caption: ["11px", { lineHeight: "14px" }],
        "metric-display": ["24px", { lineHeight: "28px" }],
        "code-lg": ["14px", { lineHeight: "20px" }],
        "code-sm": ["12px", { lineHeight: "16px" }],
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        mono: ["JetBrains Mono", "SFMono-Regular", "monospace"],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
    },
  },
  plugins: [],
};
