/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        "surface-canvas": "var(--color-surface-canvas)",
        "surface-panel": "var(--color-surface-panel)",
        "surface-recessed": "var(--color-surface-recessed)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "border-subtle": "var(--color-border-subtle)",
        "text-primary": "var(--color-text-primary)",
        "text-dim": "var(--color-text-dim)",
        "text-inverse": "var(--color-text-inverse)",
        primary: "var(--color-primary)",
        "primary-fg": "var(--color-primary-fg)",
        "primary-container": "var(--color-primary-container)",
        secondary: "var(--color-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        info: "var(--color-info)",
        "status-safe": "var(--color-status-safe)",
        "status-warn": "var(--color-status-warn)",
        "status-elevated": "var(--color-status-elevated)",
        "status-danger": "var(--color-status-danger)",
        "status-info": "var(--color-status-info)",
      },
      spacing: {
        "space-2": "2px",
        "space-4": "4px",
        "space-6": "6px",
        "space-8": "8px",
        "space-10": "10px",
        "space-12": "12px",
        "space-16": "16px",
        "space-24": "24px",
        "nav-height": "56px",
        "banner-height": "44px",
        "footer-height": "28px",
        "dock-left-width": "200px",
        "dock-right-width": "240px",
        "decision-bar-height": "52px",
      },
      fontSize: {
        "headline-lg": ["20px", { lineHeight: "28px" }],
        "headline-md": ["16px", { lineHeight: "24px" }],
        "headline-sm": ["14px", { lineHeight: "20px" }],
        "body-lg": ["14px", { lineHeight: "20px" }],
        "body-md": ["13px", { lineHeight: "18px" }],
        "body-sm": ["12px", { lineHeight: "16px" }],
        caption: ["11px", { lineHeight: "14px" }],
        "metric-display": ["24px", { lineHeight: "28px" }],
        "code-lg": ["14px", { lineHeight: "20px" }],
        "code-sm": ["12px", { lineHeight: "16px" }],
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        mono: ["JetBrains Mono", "SFMono-Regular", "monospace"],
      },
      fontWeight: {
        headline: "var(--font-weight-headline)",
      },
      boxShadow: {
        panel: "0 4px 24px var(--color-shadow)",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
    },
  },
  plugins: [],
};
